class DisneyPlusHotstar{
public static void main(String a[]){
	String kannadaSeries[]={"RadhaKrishna","Bettada Hoo Marali Manasagide Mahasangama","Hara Hara Mahadeva","Jenugudu","Bettada Hoo","bangarada-panjara","MudduManigalu","Anuraga Aralithu","Shani","Ardhangi","Yediyur-shree-siddhalingeshwara","Raaji","Manasella Neene","MahaBharata","Om Namah Shivaya"};
	System.out.print("\n"+"\n_______________________________________________\n"+"List of Kannada Series available in Disney+Hotstar:"+"\n_______________________________________________\n"+"\n"+kannadaSeries[0]+"\n"+kannadaSeries[1]+"\n"+kannadaSeries[2]+"\n"+kannadaSeries[3]+"\n"+kannadaSeries[4]+"\n"+kannadaSeries[5]+"\n"+kannadaSeries[6]+"\n"+kannadaSeries[7]+"\n"+kannadaSeries[8]+"\n"+kannadaSeries[9]+"\n"+kannadaSeries[10]+"\n"+kannadaSeries[11]+"\n"+kannadaSeries[12]+"\n"+kannadaSeries[13]+"\n"+kannadaSeries[14]+"\n*********************************************\n");
	String hindiSeries[]={"Dahan","Criminal Justice","Ghar Waapsi","Parampara","Shoorveer","Masoom","9 Hours","Home Shanthi","Rudra","Aarya","The Great Indian Murder","Raaji","Human","Legend of Hanuman","Grahan"};
	System.out.print("\n"+"\n_______________________________________________\n"+"List of Hindi Series available in Disney+Hotstar:"+"\n_______________________________________________\n"+"\n"+hindiSeries[0]+"\n"+hindiSeries[1]+"\n"+hindiSeries[2]+"\n"+hindiSeries[3]+"\n"+hindiSeries[4]+"\n"+hindiSeries[5]+"\n"+hindiSeries[6]+"\n"+hindiSeries[7]+"\n"+hindiSeries[8]+"\n"+hindiSeries[9]+"\n"+hindiSeries[10]+"\n"+hindiSeries[11]+"\n"+hindiSeries[12]+"\n"+hindiSeries[13]+"\n"+hindiSeries[14]+"\n*********************************************\n");
	String englishSeries[]={"Big Mouth","Intertwined","Adamas","The Heartthrob","Link","Parallels","Not My Fault","Doctor Lawyer","Soprano","She-Hulk","Game of Thrones","House of the Dragon","Modern Family","Family Guy","Snakes in the City"};
	System.out.print("\n"+"\n_______________________________________________\n"+"List of English Series available in Disney+Hotstar:"+"\n_______________________________________________\n"+"\n"+englishSeries[0]+"\n"+englishSeries[1]+"\n"+englishSeries[2]+"\n"+englishSeries[3]+"\n"+englishSeries[4]+"\n"+englishSeries[5]+"\n"+englishSeries[6]+"\n"+englishSeries[7]+"\n"+englishSeries[8]+"\n"+englishSeries[9]+"\n"+englishSeries[10]+"\n"+englishSeries[11]+"\n"+englishSeries[12]+"\n"+englishSeries[13]+"\n"+englishSeries[14]+"\n*********************************************\n");
}
}